### ISSUE TITLE
Alternative resource path

### ISSUE THREAD

**Issue by Sansu11** [BreakfastCraft/Spilled-Juice-Modpack#112] opened 2019-11-17 12:24 UTC
So far the options we have to gather resources beyond manual are rather limited and require a very large amount of power, which ends up putting them in late game.

Two things I can think to solve this while keeping to the "path less traveled" theme of the pack.

Chickens, they're pretty simple, low tech, but with enough mechanics to keep you from getting end game resources too early.

Bees (yes I know everyone hates bees), One good way to change access to bees is to possibly include Gendustry, and edit some of the recipes. Gonna need the accompanying resource/magical bees mods.

Instead of all the complex machinery parts, have the recipes include Steel Gears, etc, and varying drones. Like having the machine to breed isolated traits into a new queen cost something like a desert drone, a forest drone, a wintery drone, and a water drone, with 4 steel gears and a diamond.
The player still has to go explore to find all these, but it's much more accessible than the original Gendustry recipes appear.

It'd require a fair bit of tinkering to get the gendustry recipes edited, as there are a dozen or so machines, but it could work.

**Comment by slidingmike** [comment] 2019-11-17 20:32
I'm fine with moving towards bees, but this will require further input on recipes for gendustry. I'm not interested in gating them by any means, but I don't want endgame to be simple. Longevity of playing is my goal here.

**Comment by slidingmike** [comment] 2019-11-17 21:05
These mods will be included on 0.0.7 release, however the changes to recipes won't appear until 0.0.8

**Comment by slidingmike** [comment] 2019-11-17 23:42
Toph, Sansu is going to create some recipes for us to use on gendustry blocks. Mind using your craft tweaker skills to make these up when they're listed?

**Comment by topher2010** [comment] 2019-11-18 00:31
Just get me those recipes and i'll make it happen

**Comment by slidingmike** [comment] 2019-11-18 00:32
Genetic Sampler, grabs one of the traits to extract from a specimen inserted into it, important machine to get started
Recipe Suggestions, 4x lead ingots, 2x iron gear, 2x diamond gear, 1 sturdy casing

Genetic Imprinter, prints one of the traits you have extracted from the sampler onto an insterted bee, important machine to get started
Recipe Suggestions, 4x electrum ingot, 2x iron gear, 2x diamond gear, 1 sturdy casing

DNA extractor, creates liquid DNA from bees you no longer need, important machine to getting started
Recipe Suggestions, 4x silver ingot, 2x iron gear, 2x diamond gear, 1 sturdy casing

Genetic Transposer, this allows you to copy existing bee templates without consuming more bee resources, late game quality of life machine
Recipe Suggestion, 4x signalum gears, 2x diamond gears, 2 ender pearls, 1 sturdy casing

Genetic Replicator, this allows you to create bees that are ignoble(they will eventually die) which is ideal for testing purposes, late game quality of life machine
Recipe suggestions, 4x invar gears, 2 diamond gears, 2 ender pearls, 1 sturdy casing

Protien Liquifier, insert meat to get liquid protien, this is an early game feature that is usually not used heavily
recipe suggestion, 4x gold ingots, 2x iron gear, 2x saddle, 1 sturdy casing

**Comment by slidingmike** [comment] 2019-11-18 00:32
Gendustry Machine Suggestions

Basics
Requires RF to operate, so having stone-age recipe's is too low tech
It should still be cheap and attractive to go into, with escalating costs for later functions

BASIC MACHINES
Industrial Apiary, this is what houses the bees, you're ideally going to want a lot of these.
Recipe Suggestions, 4x glass blocks, 2x copper gears, 1 piston, 1 iron gear, 1 iron bars

Mutatron, this is the machine that produces the desired queen, important machine to getting started
Recipe Suggestions, 4x copper ingots, 2x iron gear, 2x diamond gear, 1 sturdy casing

Advanced Mutatron, this machine has more functions than it's basic counterpart, including multiple selectors, late game machine
Recipe Suggestions, 4x platinum gears, 2x diamond gears, 2 ender pearls, 1 mutatron

Mutagen Producer, this produces liquid mutagen which is a key resource to getting started
Recipe Suggestions, 4x tin ingots, 2x iron gear, 2x diamond gear, 1 sturdy casing

**Comment by DevJohnC** [comment] 2019-11-18 20:56
My 2 cents:

- Gendustry makes bee's stupidly easy, no matter how expensive you make the equipment, the _process_ gendustry gives you makes bee breeding and mutation trivial
- Binnie's would offer an alternative and is definitely the "path less traveled" in the modern age of modded MC
- If you're set on going with gendustry disable the mutatron/adv. mutatron entirely and force people to actually breed to mutate new bee species rather than manufacture them
- Alternatively, if you want to make bee breeding harder but tree breeding easier keep the mutatron and disable the mutation recipes for gendustry

/Edward

**Comment by Sansu11** [comment] 2019-11-18 23:04
Ed, you are 100% correct, Gendustry does make the actual breeding trivial, especially for people already familiar with the mod. There was a key thing I wanted to focus on when I suggested Forestry as an alternative resource route; making bees accessible enough that people would actually try it instead of rolling their eyes and moving on. You do still need to physically gather a lot of the bee's from the type of location the resource you're looking for comes from.

I thought of Binnies initially but came to the conclusion it was the mod less used because it was far more difficult to learn, and honestly the guides for it over time have tended to cause more confusion than when I've tried to learn it on my own. I still don't really know what I'm doing with Binnies after watching several guides.

Disabling the advanced/normal Mutatron leaves only one machine of value from the mod; the industrial apiary. Automation of the apiary can already be achieved with existing mods, and the other upgrade cards honestly aren't worth enough to have an entire mod added for.

Your last point could work, I feel like in order to keep people interested in it as a valid alternative we'd need to tweak the mutation success chances to be a bit higher which I have 0 clues if it's even possible.

The organic method of mutation is what was meant to keep people involved in the mod for longer, but actually became viewed as so brutal that the mod is avoided. It's hard to strike a balance. The recipe suggestions were to bring the complexity of getting started down.

**Comment by DevJohnC** [comment] 2019-11-18 23:17
> Disabling the advanced/normal Mutatron leaves only one machine of value from the mod; the industrial apiary

This isn't true. With the mutatron disabled you still have access to the genetic imprinting and sampling machines, enabling players to extract traits from bees and make a template for them. This is useful for making your bees produce specialities faster, or continue to work through the night, rain, or without direct sunlight, plus climate tolerances.

Additionally, the machine for producing bees from a complete template and protein is still usable (though far less useful I suppose). If you wanted to make it more useful you could get rid of pristine bees.

/Edward

**Comment by Sansu11** [comment] 2019-11-18 23:31
True, but my brain normalizes things like this.

Mutatron; enables you to quickly gain steady access to the resources from a region after you've visited there, removes RNG and feeling of time-wasting.

Genetic Manipulation; enables you to selectively superpower your existing bees, removes a large portion of time spent to generate the said resource.

Both machines are effectively being used by the bulk of players to cut down time spent to generate essentially free resources. 

Disabling the mutatron means players will have a slower time accessing new resources but will hit the original wall of frustration that caused a large portion of the mc player base to not use the mod. Players likely would just hold out until late game where laser drills, or core drills are viable with the amount of power they consume, bypassing bees entirely.

Is it possible to selectively edit individual mutations to be disabled in the Mutatron? 
It'd be fair to force players to organically mutate diamond rarity resources and above.
Or to tweak the mutation chance of the original mutation mechance to be a bit more forgiving.

**Comment by NiSiSuinegEht** [comment] 2019-11-18 23:51
Don't forget that PneumaticCraft, which is already in the pack, has the Amadron.  There's a straightforward configuration for what you can buy and sell through it that would just need someone to decide on what kind of pricing to have.

On a more selfish front, I'd like a non-tech method of resource gathering as well, something that doesn't require power generation to achieve.  Botania has the OreChid, though heavily reliant on good RNG for the rarer resources.

**Comment by topher2010** [comment] 2019-11-19 02:41
Gendustry recipes have been modified

**Comment by Winrylive** [comment] 2019-11-19 13:42
@NiSiSuinegEht Botania's OreChid isn't RNG any more than normal mining, it uses the ore generation of the world for what you'll generate with it. So if Diamonds gen is turned way up, for example, you'll get more diamonds from the OreChid. 

I like Ed's idea to see if there's a way to disable Pristine Bees. It would require people to continue to make new bees as their Queens die off, so they'd no longer have a set it and forget it Yellorium Bee for example. Which, as Ed explained can be done with a genetic template.

**Comment by NiSiSuinegEht** [comment] 2019-11-19 13:51
From what I understand, the OreChid weights the chance of a given ore based
on world gen, but what you get is still randomized.  There's no way to only
get a specific resource with it like you can with bees, chickens, Mystical
Agriculture, etc.  There's not even a way to increase the weighting of
particular ores like you can with lenses on an ET void miner.

That's not to say it isn't useful, and it's still better than mining
chunks, just not as targeted.

**Comment by Winrylive** [comment] 2019-11-19 14:19
I'd still prefer to see Binnie's instead of Gendustry and I'm all about easy! 
@Sansu11 Have you seen this? https://minecraftguides.net/Bees/ It's newer information and covers bee basics, Binnies, Gendustry and even Career Bees (which we don't have).

**Comment by Sansu11** [comment] 2019-11-19 16:13
I've seen that yes. I still find the mod really hard to wrap my head around even though the newer version is better documented.

Keep in mind the resource avenue doesn't need to be bees, that was just the one mod that almost nobody plays that came to mind.

Other ideas for alternate resource generation would be cool. Resource Trees I felt were too easy, chickens/hogs would likely be more fair than bees (I just happen to hate the aesthetic)

The Orechid isn't half bad but doesn't let you say "I want to gen x resource steadily" even with world edits to gen there's a level of RNG disparity that occurs.

I have no idea what alternative options we could include. \o/

**Comment by NiSiSuinegEht** [comment] 2019-11-19 16:41
Actually, I quite liked the resource tree mechanic, and it would be a great no-tech means of generating resources. It wouldn't be very difficult to change the sapling recipes to require an amount of the resource to be generated, and even various magical ingredients necessitating delving into those mods to obtain higher tier saplings.  I'd gladly volunteer to do the recipe modification.

**Comment by Sansu11** [comment] 2019-11-19 17:45
The only apprehension I have on Trees is that it'd need to be without the bonsai hoppers. Otherwise with some minor tweaks to some of the more rare resources, it'd be an excellent alternative to tech resource generation, which already exists late game.

Mike included Advanced Generators because it's a fabulous power genning mod that gets passed over often for big reactors. Bonsai hoppers would make a Syngas Generator self-sustained basically as soon as you got access to Redstone. You could quickly go from windmills and basic solar panels, to genning 150k+ in about an hour of crafting the things for the Syngas Generator.

**Comment by Sansu11** [comment] 2019-11-19 17:53
Alternatively could disable the wood bearing trees from bonsai hoppers? 
Not even sure if that's a thing. Or maybe change the recipe of bonsai hoppers to put it on par with the level of development needed for other tree farming options?

**Comment by NiSiSuinegEht** [comment] 2019-11-19 18:04
I've never used SynGas, but it sounds like the issue is with automated wood, rather than Tree Resources specifically. If that's the case, then it was already an issue as soon as Bonsai was added.  Automated tree farms are easily accomplished in a number of ways, many of them much faster in production than a hopping bonsai pot.

The way I'm envisioning recipe tweaks for the rarer resources, you'd need to progress a decent ways through Botania, Thaumcraft, and Psi to craft the saplings.

**Comment by Winrylive** [comment] 2019-11-19 18:50
I don't think the magic and tech chains should mix. That way people who don't want to do tech don't have to and visa versa.

**Comment by NiSiSuinegEht** [comment] 2019-11-19 21:07
Absolutely agree. That's why I was proposing changing sapling recipes to require an amount of magic mod progressing as a counterbalance to the somewhat tech heavy Binnie's/Gendustry.

**Comment by slidingmike** [comment] 2019-11-24 19:06
Closing. Binnies was added as the solution.

**Closed as completed by slidingmike** 2019-11-24 19:06 UTC
Labels: enhancement request, 1.12.2
